# action.yml
name: 'Taskwarrior'
description: 'Build TW'
inputs:
  image:
    description: "Image used for build"
    required: true
    default: "ubuntu"
runs:
  using: 'docker'
  image: 'Dockerfile-'${{ inputs.image }}

