# action.yml
name: 'Taskwarrior'
description: 'Build TW'
inputs:
  image:
    description: "Image used for build"
    required: true
    default: "ghcr.io/8-bit-fox/tw-ubuntu:18.04"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
